<?php include './shared/modales/acciones-recurso/bloquearComentarios.php'; ?>
<?php include './shared/modales/acciones-recurso/vincular.php'; ?>
<?php include './shared/modales/acciones-recurso/certificar.php'; ?>
<?php include './shared/modales/acciones-recurso/etiquetar.php'; ?>
<?php include './shared/modales/acciones-recurso/categorizar.php'; ?>
<?php include './shared/modales/acciones-recurso/enviar.php'; ?>
<?php include './shared/modales/acciones-recurso/eliminar.php'; ?>
<?php include './shared/modales/acciones-recurso/versionar.php'; ?>
<?php include './shared/modales/acciones-recurso/historial.php'; ?>
<?php include './shared/modales/acciones-recurso/compartir.php'; ?>
