<div id="modal-condiciones-uso" class="modal modal-top fade modal--wide-content modal--legal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <p class="modal-title"><span class="material-icons">privacy_tip</span>Condiciones de uso</p>
            </div>
            <div class="modal-body">
                <div class="box form activeForm" id="action">
                    <div class="box">
                        <p>Al acceder o usar el servicio, manifiestas haber leído las condiciones de acceso y reglas de convivencia de su  código ético.</p>
                        <h3>Condiciones de acceso:</h3>
                        <p>Las presentes condiciones regulan el uso del servicio web GNOSS.</p>
                        <h3>Requisitos de acceso:</h3>
                        <p>Para crear una cuenta de usuario en GNOSS, debes contar con al menos 14 años. Al registrarte en GNOSS, declaras que cumples con este requisito y estas capacitado para entender, aceptar y cumplir con las <a href="#CondicionesAcceso">condiciones de acceso</a> y <a href="#CodigoEtico">código ético</a> que rigen el funcionamiento de esta red social. Si tienes entre 14 y 18 años, necesitas una invitación a la plataforma y la autorización de tus padres o tutores legales para acceder a nuestros servicios que estarán limitados a un uso educativo. RIAM I+L Lab puede solicitarte información en cualquier momento para que demuestres tu edad real, solicitándote que nos aportes fotocopia de tu DNI o un documento equivalente. Desde RIAM I+L Lab nos reservamos el derecho a bloquear o cancelar tu perfil si no nos das esa información dentro del plazo que te digamos.</p>
                        <p>Nota: Si constatamos que un menor de 14 años está registrado como Usuario en GNOSS, eliminaremos o bloquearemos el perfil de Usuario.</p>
                        <p>Al tramitar el alta como usuario, deberás elegir unas claves de acceso. Cada vez que desees entrar en la red, el sistema te solicitará estas claves para autentificarte, siendo responsable de todas las acciones que se realicen con tu nombre de usuario y contraseña.</p>
                        <p>RIAM I+L Lab no se responsabiliza de la custodia que realices de estos elementos identificativos, ni el uso que un tercero haga de éstos sin tu consentimiento.</p>
                        <p>RIAM I+L Lab puede restringir el uso de determinados nombres de usuario que vulneren derechos de terceros.</p>
                        <h3>Procedimiento de alta en GNOSS:</h3>
                        <p>Para darte de alta en GNOSS es necesario que te registres. En la página <a href="http://www.gnoss.com">www.gnoss.com</a> podrás hacerlo pinchando en “crear cuenta”. En este proceso de registro te pediremos tus datos de acceso a la cuenta y tus datos personales. Te informaremos de la resolución de tu solicitud de registro en tu cuenta de correo de contacto.</p>
                        <p>Nota: al registrarte en GNOSS, te damos acceso también a las comunidades GNOSS siguientes: ‘Ayuda y FAQs’ donde el Equipo de GNOSS responde a las preguntas más frecuentes sobre qué se puede hacer y cómo en GNOSS y ofrece una guía de Ayuda para disfrutar de todos los servicios y contenidos del Servicio; ‘GNOSS Noticias’, nuestra Press &amp; Social Media Room donde semanalmente te informamos a través de nuestra Newsletter de las novedades en nuestro servicio y contenidos; ‘Didactalia’, el gran índice de materiales educativos en Internet para profesores, padres y alumnos desde la Educación Infantil hasta el Bachillerato y de la que semanalmente recibirás una selección con los mejores recursos educativos. Si lo deseas, puedes darte de baja de estos servicios mediante los medios habilitados para tal fin por GNOSS.</p>
                        <h3>Derechos de propiedad intelectual e industrial:</h3>
                        <p>Todos los elementos de desarrollo, programación, diseño y cualquier otro material susceptibles de propiedad intelectual que forman gnoss.com y que son necesarios para su funcionamiento se encuentran protegidos a favor de RIAM I+L Lab.</p>
                        <p>Las aportaciones y contenidos, independientemente de la naturaleza de estas, que los usuarios hagan en gnoss.com a través de las diferentes herramientas de publicación disponibles (ej. Comunidades, blogs, espacio personal público de recursos…) de las que son autores, se realizarán bajo una licencia Creative Commons en los términos de la licencia de “Reconocimiento-No comercial-Compartir bajo la misma licencia 3.0 España” que permite copiar, distribuir y comunicar públicamente la obra y hacer obras derivadas, salvo que el usuario indique lo contrario mediante el medio habilitado por gnoss.com para tal fin. Las condiciones para esta licencia pueden consultarse en <a href="http://es.creativecommons.org/licencia/" target="_blank">http://es.creativecommons.org/licencia/</a>.</p>
                        <p>En caso de que aportes materiales y contenidos no sujetos a la licencias Creative Commons, y conforme a las leyes que protegen el derecho de autor, no puedes publicar, modificar, distribuir ni reproducir materiales protegidos por estas leyes, marcas registradas o cualquier otro material que pertenezca a otras personas, incluidas las obras en coautoría, sin obtener el consentimiento previo de los titulares de dichos derechos. Como usuario que sube estos materiales eres el responsable de obtener esta autorización, sin que pueda derivarse a RIAM I+L Lab esta obtención de permisos ni podrán derivarse responsabilidades por esta causa.</p>
                        <p>GNOSS es una plataforma social que estructura todos sus datos y los expresa según los estándares y principios de la web semántica y el Linked Data Project, lo que permite la realización de búsquedas facetadas y la generación de contextos semánticos a partir del enlazado de datos. Es por ello por lo que RIAM I+L Lab se reserva el derecho a reutilizar los contenidos publicados por sus usuarios en las comunidades gratuitas de GNOSS como información contextual en otras comunidades y espacios GNOSS a través del enlazado de sus datos con terceros y viceversa, con el objeto de adaptarlos a las necesidades técnicas y operativas del Servicio, sin que esto menoscabe o restringa los derechos del autor. El usuario mantiene los derechos de autor sobre el contenido aportado.</p>
                        <h3>Protección de datos:</h3>
                        <p>Mediante la aceptación de las condiciones, el USUARIO queda informado y presta su consentimiento libre, informado, específico e inequívoco para que los datos personales que facilita con motivo de su registro a GNOSS sean tratados por RIAM I+L Lab de acuerdo con lo especificado en su&nbsp;<a href="https://www.gnoss.com/politica-privacidad" target="_blank">política de privacidad</a>.</p>
                        <h3>Finalización de servicio:</h3>
                        <p>Del mismo modo que tramitas el alta, puedes cancelar tu cuenta dirigiéndote a <a href="mailto:solicitudes@gnoss.com">solicitudes@gnoss.com</a>. Al tramitar la cancelación, tu perfil será eliminado así como la información visible para otros usuarios.</p>
                        <p>La eliminación de estos datos garantiza el cumplimiento de la política de protección de datos.</p>
                        <p>RIAM I+L Lab puede, a su entera disposición y en cualquier momento, interrumpir temporal o permanentemente el acceso y/o servicio. Esta interrupción puede realizarla sin previo aviso y por el hecho de aceptar estas condiciones al registrarte estás aceptando la desactivación de tus cuentas y perfiles en GNOSS. RIAM I+L Lab no será responsable frente a terceros o el propio usuario de la finalización o suspensión del acceso o modificación del mismo.</p>
                        <h3>Responsabilidades:</h3>
                        <p>RIAM I+L Lab no se responsabiliza de las opiniones, declaraciones, manifestaciones y comentarios que realices desde las diferentes herramientas que en esta red social ponemos a tu disposición, siendo directamente responsable el titular de las claves de acceso a la red.</p>
                        <p>Para conseguir los fines para los que GNOSS ha sido creado, queda prohibido el uso de los perfiles de usuario para actos que sean considerados como ilegales o no autorizados, que sean un ataque para otros usuarios, fraudulentos, difamatorios o que incumplan nuestro <a href="#CodigoEtico">código ético</a>.</p>
                        <p>RIAM I+L Lab se reserva el derecho a desactivar los nombres de usuarios y cuentas que hayan estado inactivos durante más de 6 meses.</p>
                        <p>En gnoss.com, el usuario podrá encontrar enlaces que le conducirán a páginas web, blogs, materiales o sitios en la web no gestionados por RIAM I+L Lab y sobre los cuales RIAM I+L Lab no ejerce control alguno, no siendo responsable del contenido, de servicios o productos ofertados desde los mismos, de la veracidad de la información que terceros ofrezcan o cualquier otro tipo de contenido que se ofrezca.</p>
                        <h3>Código ético:</h3>
                        <p>El siguiente código constituye el marco para el buen uso de GNOSS. Este código ético recoge las reglas de convivencia dentro de la red que favorecen un entorno positivo de intercambio de trabajo, opiniones y valores.</p>
                        <p>Su objetivo principal es establecer unas directrices que permitan proteger al máximo la privacidad, los derechos que por ley son reconocidos y la experiencia global de la red, siendo un complemento a las <a href="#CondicionesAcceso">condiciones de acceso</a>.</p>
                        <p>Si detectas cualquier violación por parte de un tercero de las normas de la red, podrás comunicárnoslo enviando un correo electrónico a <a href="mailto:reclamaciones@gnoss.com">reclamaciones@gnoss.com</a>.</p>
                        <p>En GNOSS favorecemos el intercambio de conocimiento de forma libre y sin ningún tipo de restricción inicialmente. No obstante, existen las limitaciones legales y contractuales relativas al contenido y el comportamiento entre usuarios.</p>
                        <h3>Identidad del usuario:</h3>
                        <p>Debes facilitarnos datos ciertos al crear tu perfil y no mentirnos con la edad. Ya sabes, conforme a lo establecido en las condiciones de acceso, que los menores de 14 años no deben acceder a GNOSS.</p>
                        <h3>Contenidos:</h3>
                        <p>Con igual conformidad a lo establecido en las condiciones de acceso y uso, no debes intercambiar, compartir, guardar o favorecer, a través de nuestra red, materiales, opiniones o comentarios que infrinjan la normativa legal y las costumbres.</p>
                        <h3>Invitaciones a la Comunidad:</h3>
                        <p>Cuando invites a participar a otras personas a una comunidad en la que colaboras, debes asegurarte de que conocen y aceptan estas condiciones de uso. Si GNOSS estima que se han infringido las normas de la comunidad por alguna de las personas invitadas, puede suspender o cancelar ambos perfiles para salvaguarda de los intereses generales de la comunidad en la que están participando y la integridad de GNOSS.</p>
                        <h3>Usos de la comunidad:</h3>
                        <p>La invitación y el uso de las diferentes comunidades gestionadas por nuestra red social no pueden usarse para fines comerciales, salvo que RIAM I+L Lab lo permita de forma expresa.</p>
                        <h3>Actos no permitidos:</h3>
                        <p>Queda prohibido, por lo que será de tu exclusiva responsabilidad, el acceso o la utilización del Servicio con fines ilegales o no autorizados. Más específicamente, y sin que el siguiente listado tenga carácter absoluto, queda prohibido:</p>
                        <ul>
                            <li>Difamar, acosar, intimidar o amenazar a otros usuarios de la red de GNOSS o a terceros ajenos a ella.</li>
                            <li>Utilizar datos personales e íntimos de otras personas con fines diferentes a los que el entorno de la comunidad a la que perteneces determine.</li>
                            <li>Usar la red como herramienta de intercambio de materiales o informaciones que sean obscenos, ilícitos, calumniosos, inmorales y/o inapropiados.</li>
                            <li>Intercambiar materiales que conforme a la ley de propiedad intelectual pertenezcan a un tercero sin su consentimiento. Del mismo modo, no podrás retirar los avisos legales sobre derechos de autor, marcas registradas o de otros derechos afines.</li>
                            <li>Usar GNOSS como difusor de virus, envío de spam, programas maliciosos, así como archivos y/o programas que interrumpan, dañen o limiten la operatividad de la propia red o de cualquier software, hardware o equipo de telecomunicaciones. Del mismo modo, no realizarás ninguna acción que pueda dañar, sobrecargar o deteriorar la red GNOSS.</li>
                            <li>Crear una cuenta con identidad falsa o mediante la usurpación de identidad de otra persona o entidad.</li>
                            <li>Utilizar cualquier herramienta o servicio de GNOSS como instrumento para publicar, repetir o duplicar sistema y/o automáticamente contenidos.</li>
                        </ul>
                        <p>La realización de cualquiera de los anteriores comportamientos por tu parte permitirá a RIAM, dependiendo de la gravedad y según su criterio, suspender o cancelar tu perfil de forma inmediata y, en su caso, retirar contenidos en los perfiles que vulneren este listado de actos no permitidos.</p>
                        <p>Llegado el caso, en aplicación de lo dispuesto en el párrafo anterior, RIAM I+L Lab suspenderá o cancelará tu perfil automáticamente. Dicho acto no te daría derecho a indemnización alguna. A todos estos efectos, te informamos que RIAM I+L Lab podrá poner en conocimiento y colaborar oportunamente con las autoridades policiales y judiciales competentes si detectase cualquier infracción de la legislación vigente o si tuviera sospecha de delito.</p>
                        <p>Por último, queremos recordarte que RIAM I+L Lab no se responsabiliza de las opiniones, declaraciones, manifestaciones y comentarios que realices desde las diferentes herramientas que en esta red social ponemos a tu disposición, siendo directamente responsable el titular de las claves de acceso a la red.</p>
                    </div>
                </div>
                <span class="btn btn-primary " data-dismiss="modal" aria-label="Close">
                    Cerrar
                </span>
            </div>
        </div>
    </div>
</div>